### ISSUE TITLE
Sftp can't upload big files

### ISSUE THREAD

**Issue by EbeyH** [mikaelliljedahl/freesftpsharp#5]
After window packet size has end, end SSH_WINDOW_ADJUST has sent.
I received 1 or 2 unparsed messages. 
And upload fails.

**Comment by mikaelliljedahl** [comment]
Which client software are you using?
You can upload small files but not larger ones? 
What is big? 1 Mb or 1 Gb?
Is the SSH_WINDOW_ADJUST related to the upload big files problem?

**Comment by EbeyH** [comment]
Over 1mb.
from what I saw it depends on maxWindowSize in window adjust definition.
I'm using filezilla client and core ftp(winScp isn't work good but this is
another problem)

**Comment by EbeyH** [comment]
And yes. After I sent the WindowAdjustMessage, I get some 1 or 2 sftp
unparsed messages with small size than usual

**Comment by mikaelliljedahl** [comment]
Inside FxSsh.Session these 2 constants are declared

        internal const int InitialLocalWindowSize = LocalChannelDataPacketSize * 32;
        internal const int LocalChannelDataPacketSize = 1024 * 32;

InitialLocalWindowSize is pretty much exactly 1 Mb.


The implementation originally came from: 
https://github.com/0xFireball/SSHServer/blob/master/FxSsh/Services/Channel.cs
and related
https://github.com/0xFireball/SSHServer/blob/master/FxSsh/Messages/Connection/ChannelWindowAdjustMessage.cs

Maybe method ClientAdjustWindow or method ServerAttemptAdjustWindow is involved in changing the window size but I actually don't have a clue what to change to get it to work.

BR
Mikael

**Comment by mikaelliljedahl** [comment]
I made a litte test and changing the InitialLocalWindowSize constant did the trick. I could successfully upload a 30 Mb file using FileZilla. I have updated the repo.

**Comment by EbeyH** [comment]
Thanks I'll check next week.
